spring:
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET, POST, PATCH, PUT, DELETE
      allowed-headers: "*"
  main:
    allow-bean-definition-overriding: true
  restTemplate:
    messageConverters:
      - jackson
      - xml
    requestFactory:
      timeout: 5000
  datasource:
    url: jdbc:postgresql://cilyupwyygux.us-east-1.rds.amazonaws.com:5432/calculator
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  address: localhost
  port: 8081

client:
  randomOrg:
    url: https://www.random.org/strings/?num=1&len=10&digits=on&unique=on&format=plain&rnd=new